# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[dev]
  command = "npm run dev" # Command to start your dev server
  port = 5173             # Port that your dev server runs on
